### ISSUE TITLE
Implement a fallback method when parsing goes wrong

### ISSUE THREAD

**Issue by jeroenverfallie** [cerebral-legacy/cerebral-module-router#98]
I'd like you to consider implementing a fallback method, when the parsing goes wrong.
Right now, if your app gets hit by a broke query state, due to social media, message caps, broken links in newsletters, etc, you hit an exception on URLON, and your app never gets rendered, as you can't catch this exception.

So, consider adding something like:

```
Router({
    onParseError: () => {}
})
```

I know you can hook before the router triggers, but there's too many edge cases to handle manually cfr. #84

**Comment by Guria** [comment]
@jeroenverfallie do you have example of `onParseError`? What we should expose to it except 'url'?

**Comment by jeroenverfallie** [comment]
Ideally this would work like middleware, so you could correct the url and pass it to the parser again, thus, the only thing you do is fix the url (and possibly track something non related to the cerebral routing).

```js
Router({
    handleParseException: (url, redirect) => {
        // fix the url
        const fixedUrl = url;
        redirect(fixedUrl);

        // unfixable?
        redirect('/');
    }
})
```
